/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_flyscale_chapter_4_3_PngView */

#ifndef _Included_com_flyscale_chapter_4_3_PngView
#define _Included_com_flyscale_chapter_4_3_PngView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_flyscale_chapter_4_3_PngView
 * Method:    getStringFromJNI
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_flyscale_chapter_14_13_PngView_getStringFromJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_flyscale_chapter_4_3_PngView
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_flyscale_chapter_14_13_PngView_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_flyscale_chapter_4_3_PngView
 * Method:    setSurface
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_flyscale_chapter_14_13_PngView_setSurface
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_flyscale_chapter_4_3_PngView
 * Method:    resetSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_flyscale_chapter_14_13_PngView_resetSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_flyscale_chapter_4_3_PngView
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_flyscale_chapter_14_13_PngView_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
